services:
  web_php82:
    build: ./ubuntu_web_php82
    container_name: ubuntu_web_php82
    ports:
      - "8082:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: ubuntu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ubuntu_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
